# Generated by Django 3.2.25 on 2024-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_auto_20240401_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='sizes',
        ),
        migrations.AddField(
            model_name='sneakers',
            name='sizes',
            field=models.CharField(default='40', max_length=250, verbose_name='Available Sizes'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
